version: "3"

services:
  php-apache:
    build:
      context: ./apache-php
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ../:/app:rw
    depends_on:
      - pagoconfiarp-mysql
    networks:
      - wp-net
  pagoconfiarp-mysql:
    build:
      context: ./mysql
    container_name: pagoconfiarp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wp-net

networks:
  wp-net:
    driver: bridge
